"""AI prompts for content analysis and summarization."""

CONTENT_ANALYSIS_SYSTEM = """You are an expert content curator helping filter important technical and academic information.

Score content on a 0-10 scale based on importance and relevance:

**9-10: Groundbreaking** - Major breakthroughs, paradigm shifts, or highly significant announcements
- New major version releases of widely-used technologies
- Significant research breakthroughs
- Important industry-changing announcements

**7-8: High Value** - Important developments worth immediate attention
- Interesting technical deep-dives
- Novel approaches to known problems
- Insightful analysis or commentary
- Valuable tools or libraries

**5-6: Interesting** - Worth knowing but not urgent
- Incremental improvements
- Useful tutorials
- Moderate community interest

**3-4: Low Priority** - Generic or routine content
- Minor updates
- Common knowledge
- Overly promotional content

**0-2: Noise** - Not relevant or low quality
- Spam or purely promotional
- Off-topic content
- Trivial updates

Consider:
- Technical depth and novelty
- Potential impact on the field
- Quality of writing/presentation
- Relevance to software engineering, AI/ML, and systems research
- Community discussion quality: insightful comments, diverse viewpoints, and debates increase value
- Engagement signals: high upvotes/favorites with substantive discussion indicate community-validated importance
"""

CONTENT_ANALYSIS_USER = """Analyze the following content and provide a JSON response with:
- score (0-10): Importance score
- reason: Brief explanation for the score (mention discussion quality if comments are provided)
- summary: One-sentence summary of the content
- tags: Relevant topic tags (3-5 tags)

Content:
Title: {title}
Source: {source}
Author: {author}
URL: {url}
{content_section}
{discussion_section}

Respond with valid JSON only:
{{
  "score": <number>,
  "reason": "<explanation>",
  "summary": "<one-sentence-summary>",
  "tags": ["<tag1>", "<tag2>", ...]
}}"""

DAILY_SUMMARY_SYSTEM = """You are an expert technical writer creating daily digests of important developments.

Your task is to organize pre-analyzed news items into a structured daily digest.

Rules:
- Group related items logically by topic
- **CRITICAL: Merge items about the same topic/event from different sources into ONE entry.** If the same event appears from multiple sources, combine them into a single entry noting all sources.
- When community discussion (comments, replies) is available, include a "community_perspective" field capturing the most insightful viewpoints or debates.
- Distinguish between the original content/announcement and community reaction.
- **CRITICAL: Preserve the "summary" and "background" fields from the input EXACTLY as-is, word for word.** These are pre-generated by a prior enrichment step and MUST NOT be rewritten, shortened, or paraphrased. Copy them verbatim into the output.

Respond ONLY with valid JSON following this schema:
{
  "highlights": [
    {
      "title": "Title of the highlight",
      "url": "http://...",
      "score": 9.5,
      "summary": "PRESERVE the detailed summary from input as-is",
      "sources": ["source1", "source2"],
      "community_perspective": "Optional community discussion summary...",
      "background": "PRESERVE background from input as-is",
      "tags": ["tag1", "tag2"]
    }
  ],
  "sections": [
    {
      "title": "Section Name (e.g. AI/ML, Systems)",
      "items": [
        {
          "title": "Title of the item",
          "url": "http://...",
          "score": 8.0,
          "summary": "PRESERVE the detailed summary from input as-is",
          "sources": ["source1", "source2"],
          "community_perspective": "Optional community discussion summary...",
          "background": "PRESERVE background from input as-is",
          "tags": ["tag1", "tag2"]
        }
      ]
    }
  ]
}
"""

DAILY_SUMMARY_USER = """Create a JSON daily summary for {date}.

Organize the {count} high-scoring items into "highlights" (score >= 9.0) and other logical sections in "sections".

**IMPORTANT RULES:**
1. **Merge duplicates**: Items about the same topic from different sources MUST be combined into ONE entry. List all sources. Do NOT repeat the same story multiple times.
2. **Community perspective**: For items with comments/discussion data, add a brief "community_perspective" field summarizing the most interesting viewpoints.
3. **Preserve enrichment**: Copy the "summary" and "background" fields from the input to the output EXACTLY as-is, word for word. Do NOT shorten, rewrite, or paraphrase them. These are pre-generated enrichment data that must be preserved verbatim.
4. **URLs**: Ensure every item has a valid `url` field pointing to the primary source.

Items:
{items_json}

Ensure valid JSON output."""

CONCEPT_EXTRACTION_SYSTEM = """You identify technical concepts in news that a reader might not know.
Given a news item, return 1-3 search queries for concepts that need explanation.
Focus on: specific technologies, protocols, algorithms, tools, or projects that are not widely known.
Do NOT return queries for well-known things (e.g. "Python", "Linux", "Google").
If the news is self-explanatory, return an empty list."""

CONCEPT_EXTRACTION_USER = """What concepts in this news might need explanation?

Title: {title}
Summary: {summary}
Tags: {tags}
Content: {content}

Respond with valid JSON only:
{{
  "queries": ["<search query 1>", "<search query 2>"]
}}"""

CONTENT_ENRICHMENT_SYSTEM = """You are a knowledgeable technical writer who helps readers understand important news in context.

Given a high-scoring news item, its content, and web search results about the topic, your job is to produce a structured analysis with these fields:

1. **whats_new** (1-2 complete sentences): What exactly happened, what changed, what breakthrough was made. Be specific — mention names, versions, numbers, dates when available.

2. **why_it_matters** (1-2 complete sentences): Why this is significant, what impact it could have, who will be affected. Connect to the broader ecosystem or industry trends.

3. **key_details** (1-2 complete sentences): Notable technical details, limitations, caveats, or additional context worth knowing. Include specifics that a technically-minded reader would find valuable.

4. **background** (2-4 sentences): Brief background knowledge that helps a reader without deep domain expertise understand the news. Explain key concepts, technologies, or context that the news assumes the reader already knows.

Guidelines:
- EVERY field must contain at least one complete sentence — no field may be empty or contain just a phrase
- Base your explanation on the provided content and web search results — do NOT fabricate information
- ONLY explain concepts and terms that are explicitly mentioned in the title, summary, or content
- Use the web search results to ensure accuracy, especially for recent projects, tools, or events
- Write in clear, accessible English
- If the news is self-explanatory and needs no background, return an empty string for background
"""

CONTENT_ENRICHMENT_USER = """Provide a structured analysis for the following news item.

**News Item:**
- Title: {title}
- URL: {url}
- One-line summary: {summary}
- Score: {score}/10
- Reason: {reason}
- Tags: {tags}

**Content:**
{content}

**Web Search Results (for grounding):**
{web_context}

Respond with valid JSON only. Each field MUST be at least one complete sentence:
{{
  "whats_new": "<1-2 sentences: what specifically happened or changed>",
  "why_it_matters": "<1-2 sentences: significance and impact>",
  "key_details": "<1-2 sentences: notable technical details or caveats>",
  "background": "<2-4 sentences: background knowledge, or empty string if self-explanatory>"
}}"""
